EXCEL_FILE_PATH = "resources/annotations.xlsx"
HTML_FILE_PATH = "resources/templateHTML.html"

ANNOTATION_SHEET = "annotations"
ANNOTATION_COLUMN = "annotation"
ELEMENT_SHEET = "elements"
ELEMENT_COLUMN = "annotation"
ELEMENT_MEANING_COLUMN = "meaning"
ELEMENT_HTML_COLUMN = "html"
STATE_SHEET = "states"
STATE_COLUMN = "annotation"
FLOW_SHEET = "flows"
FLOW_COLUMN = "flow"
EVENT_SHEET = "events"
EVENT_COLUMN = "event"